FactoryBot.define do
  factory :tap_template do
    name "MyString"
    article_number "MyString"
    dn "MyString"
    input_connection "MyString"
    output_connection "MyString"
    double_jacket_connection "MyString"
    inclination_input_offset_output "MyString"
    face_to_face "MyString"
    maximal_pressure 1.5
    test_pressure 1.5
    maximum_temperature 1.5
    pressure_at_maximum_temperature 1.5
    minimum_temperature 1.5
    pressure_at_minimum_temperature 1.5
    fluid_nature 1
    fluid_danger_group 1
    unstable_gas false
    risk_category_according_to_DESP_2014_68 1
    manual_control "MyString"
    actuator "MyString"
    pneumatic_actuator_pressure 1.5
    position_detector "MyString"
    open_position "MyString"
    close_position "MyString"
    piloting "MyString"
    other_instrumentation "MyString"
    shell "MyString"
    double_shell "MyString"
    shutter_cover "MyString"
    seat "MyString"
    cable_gland_packing "MyString"
    seals "MyString"
    atex "MyString"
    other_special_requirements "MyString"
    other_controls "MyString"
    other "MyString"
  end
end
