
version: "3.7"
 
services:

  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: notneeded
      POSTGRES_USER: postgres_user
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  web:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
      dockerfile: production.Dockerfile
    depends_on:
      - postgres
      - redis
    links:
      - postgres:db
    ports:
      - '8010:3000'
    entrypoint: /usr/src/app/bin/start
    env_file:
      - .env
    # Keeps the stdin open, so we can attach to our app container's process and
    # do stuff such as `byebug` or `binding.pry`:
    stdin_open: true
    # Allows us to send signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres_user:notneeded@db:5432/web
      RAILS_LOG_TO_STDOUT: "true"
volumes:
  postgres:
  redis:
